version: "3.8"
services:
  azurlite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    networks:
      - azurite-net

  codepush-api:
    container_name: codepush-api
    build:
      context: ./
    image: pm2-codepush-api-img
    ports:
      - 3000:3000
    networks:
      - azurite-net
networks:
  azurite-net:
    driver: bridge
